name: minio
services:
    minio:
        container_name: minio
        image: quay.io/minio/minio
        command: server /data --console-address ":9001"
        environment:
            - MINIO_ROOT_USER=webserver
            - MINIO_ROOT_PASSWORD=webserver#b512
        ports:
            - 9000:9000
            - 9001:9001
        volumes:
            - ./data:/data
